name: core
description: Core shared functionality and utilities.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  auto_route: ^9.2.2
  dio: ^5.7.0
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.8.1
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  json_serializable: ^6.7.1
  drift_dev: ^2.20.0
