name: details
description: Product details feature module.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  auto_route: ^9.2.2
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.12
  auto_route_generator: ^9.0.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.6.3
